/**
 * Copyright:
 *  This software is licensed under the Mulan Permissive Software License, Version 2 (MulanPSL-2.0).
 *  You may obtain a copy of the License at:http://license.coscl.org.cn/MulanPSL2
 *  As stipulated by the MulanPSL-2.0, you are granted the following freedoms:
 *      To copy, use, and modify the software;
 *      To redistribute the software.
 *
 * Author: Generated by Copilot
 */

#include "TimeStruct.h"
#include "TimeConvert.h"
#include "GnssStruct.h"
#include "NavEphGPS.hpp"
#include "RinexNavStore.hpp"
#include "SP3Store.hpp"
#include "StringUtils.h"
#include <fstream>

int main(int argc, char* argv[]) {
    // 加载RNX导航文件 (广播星历)
    string navFile = "../data/BRDC00IGS_R_20250010000_01D_MN.rnx";
    RinexNavStore navStore;
    navStore.loadFile(navFile);

    // 加载SP3精密星历
    string sp3File = "../data/COD0MGXFIN_20250010000_01D_05M_ORB.SP3";
    SP3Store sp3Store;
    sp3Store.loadSP3File(sp3File);

    // 获取所有卫星
    SatIDSet allSats = sp3Store.getSatSet();

    // 定义起始时间：2025-01-01 00:00:00
    CivilTime startTime(2025, 1, 1, 0, 0, 0.0);
    CommonTime startCT = CivilTime2CommonTime(startTime);
    startCT.setTimeSystem(TimeSystem::GPS);

    // 结束时间：2025-01-01 23:59:59
    CivilTime endTime(2025, 1, 1, 23, 59, 59.0);
    CommonTime endCT = CivilTime2CommonTime(endTime);
    endCT.setTimeSystem(TimeSystem::GPS);

    // 间隔30秒
    double interval = 30.0;

    // 打开输出文件
    ofstream outFile("D:\\Clion\\gps_diffs.txt");
    outFile << "SatID avg_pos_x avg_pos_y avg_pos_z avg_vel_x avg_vel_y avg_vel_z\n";

    // 遍历所有GPS卫星
    for (const auto& sat : allSats) {
        if (sat.system != "G") continue;  // 只处理GPS卫星

        Vector3d sumPosDiff(0.0, 0.0, 0.0);
        Vector3d sumVelDiff(0.0, 0.0, 0.0);
        int numPoints = 0;

        CommonTime current = startCT;
        while (current <= endCT) {
            try {
                // 获取广播星历的Xvt
                Xvt xvtNav = navStore.getXvt(sat, current);

                // 获取SP3的Xvt
                Xvt xvtSP3 = sp3Store.getXvt(sat, current);

                // 计算差
                Vector3d diffPos = xvtNav.getPos() - xvtSP3.getPos();
                Vector3d diffVel = xvtNav.getVel() - xvtSP3.getVel();

                sumPosDiff += diffPos;
                sumVelDiff += diffVel;
                numPoints++;
            } catch (...) {
                // 如果某个时间点数据缺失，跳过
            }

            current += interval;
        }

        if (numPoints > 0) {
            Vector3d avgPosDiff = sumPosDiff / numPoints;
            Vector3d avgVelDiff = sumVelDiff / numPoints;

            outFile << sat << " " << avgPosDiff.x() << " " << avgPosDiff.y() << " " << avgPosDiff.z()
                    << " " << avgVelDiff.x() << " " << avgVelDiff.y() << " " << avgVelDiff.z() << "\n";

            cout << "Processed " << sat << " with " << numPoints << " points\n";
        }
    }

    outFile.close();
    cout << "Results saved to gps_diffs.txt\n";

    return 0;
}