/**
 * Copyright:
 *  This software is licensed under the Mulan Permissive Software License, Version 2 (MulanPSL-2.0).
 *  You may obtain a copy of the License at:http://license.coscl.org.cn/MulanPSL2
 * As stipulated by the MulanPSL-2.0, you are granted the following freedoms:
 *      To copy, use, and modify the software;
 *      To redistribute the software.
 *
 * Author: Generated by Copilot
 */

#include "TimeStruct.h"
#include "TimeConvert.h"
#include "GnssStruct.h"
#include "NavEphBDS.hpp"
#include "RinexNavStore.hpp"
#include "SP3Store.hpp"
#include <fstream>

static bool fileExists(const std::string &path) {
    std::ifstream in(path);
    return in.good();
}

static std::string resolveDataFile(const std::string &relativePath, const char *argv0) {
    if (fileExists(relativePath)) {
        return relativePath;
    }

    std::string exePath = argv0 ? argv0 : std::string();
    std::string exeDir;
    size_t pos = exePath.find_last_of("\\/");
    if (pos == std::string::npos) {
        exeDir = ".";
    } else {
        exeDir = exePath.substr(0, pos);
    }

    std::string candidate = exeDir + "/" + relativePath;
    if (fileExists(candidate)) {
        return candidate;
    }

    if (relativePath.size() > 3 && relativePath[0] == '.' && relativePath[1] == '.' && relativePath[2] == '/') {
        std::string alt = exeDir + relativePath.substr(2);
        if (fileExists(alt)) {
            return alt;
        }
    }

    return relativePath;
}

int main(int argc, char* argv[]) {
    // 加载导航文件
    string navFile = resolveDataFile("../data/BRDC00IGS_R_20250010000_01D_MN.rnx", argv[0]);
    cout << "Loading navigation file: " << navFile << endl;
    RinexNavStore navStore;
    navStore.loadFile(navFile);

    // 加载SP3文件
    string sp3File = resolveDataFile("../data/WUM0MGXFIN_20250010000_01D_05M_ORB.SP3", argv[0]);
    cout << "Loading SP3 file: " << sp3File << endl;
    SP3Store sp3Store;
    sp3Store.loadSP3File(sp3File);

    // 获取所有卫星
    SatIDSet allSats = sp3Store.getSatSet();
    cout << "Loaded " << allSats.size() << " satellites from SP3 file" << endl;
    cout << "BDS satellites found: ";
    int bdsSatCount = 0;
    for (const auto& sat : allSats) {
        if (sat.system == "C") {
            cout << sat << " ";
            bdsSatCount++;
        }
    }
    cout << endl;
    cout << "Total BDS satellites: " << bdsSatCount << endl;

    // 设置时间范围
    CivilTime startTime(2025, 1, 1, 0, 0, 0.0, TimeSystem::GPS); // 使用GPS时间系统
    CommonTime startCT = CivilTime2CommonTime(startTime);

    CivilTime endTime(2025, 1, 1, 23, 59, 59.0, TimeSystem::GPS); // 使用GPS时间系统
    CommonTime endCT = CivilTime2CommonTime(endTime);

    double interval = 30.0;

    // 修改输出文件路径为相对路径
    ofstream outFile("../data/bds_diffs.txt");
    outFile << "SatID avg_pos_x avg_pos_y avg_pos_z avg_vel_x avg_vel_y avg_vel_z\n";

    for (const auto& sat : allSats) {
        if (sat.system != "C") continue;

        Vector3d sumPosDiff(0.0, 0.0, 0.0);
        Vector3d sumVelDiff(0.0, 0.0, 0.0);
        int numPoints = 0;
        int errorCount = 0;

        CommonTime current = startCT;
        while (current <= endCT) {
            try {
                Xvt xvtNav = navStore.getXvt(sat, current);
                Xvt xvtSP3 = sp3Store.getXvt(sat, current); // 直接使用相同的时间

                Vector3d diffPos = xvtNav.getPos() - xvtSP3.getPos();
                Vector3d diffVel = xvtNav.getVel() - xvtSP3.getVel();

                sumPosDiff += diffPos;
                sumVelDiff += diffVel;
                numPoints++;
            } catch (const std::exception& e) {
                errorCount++;
                // 每100个错误输出一次，避免输出过多
                if (errorCount % 100 == 0) {
                    cerr << "Error processing " << sat << " at " << current << ": " << e.what() << endl;
                }
            } catch (...) {
                errorCount++;
                if (errorCount % 100 == 0) {
                    cerr << "Unknown error processing " << sat << " at " << current << endl;
                }
            }
            current += interval;
        }

        if (numPoints > 0) {
            Vector3d avgPosDiff = sumPosDiff / numPoints;
            Vector3d avgVelDiff = sumVelDiff / numPoints;

            outFile << sat << " " << avgPosDiff.x() << " " << avgPosDiff.y() << " " << avgPosDiff.z()
                    << " " << avgVelDiff.x() << " " << avgVelDiff.y() << " " << avgVelDiff.z() << "\n";

            cout << "Processed " << sat << " with " << numPoints << " points, " << errorCount << " errors\n";
        } else {
            cout << "No valid data for " << sat << ", " << errorCount << " errors\n";
        }
    }

    outFile.close();
    cout << "Results saved to ../data/bds_diffs.txt\n";
    return 0;
}
